name: cameratraps-env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - asttokens=2.2.1=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.5=pyhd8ed1ab_0
  - blas=2.117=mkl
  - blas-devel=3.9.0=17_win64_mkl
  - brotli=1.0.9=hcfcfb64_9
  - brotli-bin=1.0.9=hcfcfb64_9
  - brotli-python=1.0.9=py38hd3f51b4_9
  - bzip2=1.0.8=h8ffe710_4
  - ca-certificates=2023.7.22=h56e8100_0
  - certifi=2023.7.22=pyhd8ed1ab_0
  - charset-normalizer=3.2.0=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.1.4=pyhd8ed1ab_0
  - contourpy=1.1.0=py38hb1fd069_0
  - cudatoolkit=11.3.1=hf2f0253_12
  - cudnn=8.1.0.77=h3e0f4f4_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - debugpy=1.6.8=py38hd3f51b4_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - fonttools=4.42.0=py38h91455d4_0
  - freeglut=3.2.2=h63175ca_2
  - freetype=2.12.1=h546665d_1
  - humanfriendly=10.0=py38haa244fe_4
  - icu=69.1=h0e60522_0
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=6.8.0=pyha770c72_0
  - importlib-resources=6.0.0=pyhd8ed1ab_1
  - importlib_metadata=6.8.0=hd8ed1ab_0
  - importlib_resources=6.0.0=pyhd8ed1ab_1
  - intel-openmp=2023.2.0=h57928b3_49496
  - ipykernel=6.25.0=pyh6817e22_0
  - ipython=8.12.2=pyh08f2357_0
  - jasper=2.0.33=hc2e4405_1
  - jedi=0.19.0=pyhd8ed1ab_0
  - jpeg=9e=hcfcfb64_3
  - jsonpickle=3.0.0=pyhd8ed1ab_0
  - jupyter_client=8.3.0=pyhd8ed1ab_0
  - jupyter_core=5.3.1=py38haa244fe_0
  - kiwisolver=1.4.4=py38hb1fd069_1
  - lcms2=2.12=h2a16943_0
  - lerc=3.0=h0e60522_0
  - libblas=3.9.0=17_win64_mkl
  - libbrotlicommon=1.0.9=hcfcfb64_9
  - libbrotlidec=1.0.9=hcfcfb64_9
  - libbrotlienc=1.0.9=hcfcfb64_9
  - libcblas=3.9.0=17_win64_mkl
  - libdeflate=1.10=h8ffe710_0
  - libffi=3.4.2=h8ffe710_5
  - libhwloc=2.9.2=nocuda_h15da153_1008
  - libiconv=1.17=h8ffe710_0
  - liblapack=3.9.0=17_win64_mkl
  - liblapacke=3.9.0=17_win64_mkl
  - libopencv=4.5.5=py38h541d912_9
  - libpng=1.6.39=h19919ed_0
  - libprotobuf=3.20.3=h12be248_0
  - libsodium=1.0.18=h8d14728_1
  - libsqlite=3.42.0=hcfcfb64_0
  - libtiff=4.3.0=hc4061b1_4
  - libuv=1.44.2=hcfcfb64_1
  - libwebp=1.3.1=hcfcfb64_0
  - libwebp-base=1.3.1=hcfcfb64_0
  - libxcb=1.13=hcd874cb_1004
  - libxml2=2.11.4=hc3477c8_0
  - libzlib=1.2.13=hcfcfb64_5
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - matplotlib=3.7.2=py38haa244fe_0
  - matplotlib-base=3.7.2=py38h2d9580e_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mkl=2022.1.0=h6a75c08_874
  - mkl-devel=2022.1.0=h57928b3_875
  - mkl-include=2022.1.0=h6a75c08_874
  - msys2-conda-epoch=20160418=1
  - munkres=1.1.4=pyh9f0ad1d_0
  - nb_conda_kernels=2.3.1=py38haa244fe_2
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - numpy=1.24.4=py38h1d91fd2_0
  - opencv=4.5.5=py38haa244fe_9
  - openjpeg=2.5.0=hb211442_0
  - openssl=1.1.1v=hcfcfb64_0
  - packaging=23.1=pyhd8ed1ab_0
  - pandas=2.0.3=py38hf08cf0d_1
  - parso=0.8.3=pyhd8ed1ab_0
  - patsy=0.5.3=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=9.1.0=py38hd8e0db4_2
  - pip=23.2.1=pyhd8ed1ab_0
  - platformdirs=3.10.0=pyhd8ed1ab_0
  - pooch=1.7.0=pyha770c72_3
  - prompt-toolkit=3.0.39=pyha770c72_0
  - prompt_toolkit=3.0.39=hd8ed1ab_0
  - psutil=5.9.5=py38h91455d4_0
  - pthread-stubs=0.4=hcd874cb_1001
  - pthreads-win32=2.9.1=hfa6e2cd_3
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - py-opencv=4.5.5=py38h4317176_9
  - pygments=2.15.1=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyqt=5.12.3=py38h7ae7562_4
  - pyreadline3=3.4.1=py38haa244fe_2
  - pysocks=1.7.1=pyh0701188_6
  - python=3.8.15=h0269646_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python_abi=3.8=3_cp38
  - pytorch=1.10.1=py3.8_cuda11.3_cudnn8_0
  - pytorch-mutex=1.0=cuda
  - pytz=2023.3=pyhd8ed1ab_0
  - pywin32=304=py38hd3f51b4_2
  - pyyaml=6.0=py38h91455d4_5
  - pyzmq=25.1.0=py38ha85f68a_0
  - qt=5.12.9=h556501e_6
  - requests=2.31.0=pyhd8ed1ab_0
  - scipy=1.10.1=py38h1aea9ed_3
  - seaborn=0.12.2=hd8ed1ab_0
  - seaborn-base=0.12.2=pyhd8ed1ab_0
  - setuptools=58.5.3=py38haa244fe_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.42.0=hcfcfb64_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statsmodels=0.14.0=py38h634f036_1
  - tbb=2021.10.0=h91493d7_0
  - tk=8.6.12=h8ffe710_0
  - torchvision=0.11.2=py38_cu113
  - tornado=6.3.2=py38h91455d4_0
  - tqdm=4.65.0=pyhd8ed1ab_1
  - traitlets=5.9.0=pyhd8ed1ab_0
  - typing-extensions=4.7.1=hd8ed1ab_0
  - typing_extensions=4.7.1=pyha770c72_0
  - ucrt=10.0.22621.0=h57928b3_0
  - unicodedata2=15.0.0=py38h91455d4_0
  - vc=14.3=h64f974e_17
  - vc14_runtime=14.36.32532=hfdfe4a8_17
  - vs2015_runtime=14.36.32532=h05e6639_17
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - wheel=0.41.0=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=pyhd8ed1ab_6
  - xorg-libxau=1.0.11=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - xz=5.2.6=h8d14728_0
  - yaml=0.2.5=h8ffe710_2
  - zeromq=4.3.4=h0e60522_1
  - zipp=3.16.2=pyhd8ed1ab_0
  - zlib=1.2.13=hcfcfb64_5
  - zstd=1.5.2=h12be248_7
  - pip:
      - absl-py==1.4.0
      - anyio==4.0.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.2.3
      - astunparse==1.6.3
      - async-lru==2.0.4
      - attrs==23.1.0
      - babel==2.12.1
      - beautifulsoup4==4.12.2
      - bleach==6.0.0
      - cachetools==5.3.1
      - cffi==1.15.1
      - customtkinter==5.2.0
      - darkdetect==0.8.0
      - defusedxml==0.7.1
      - exceptiongroup==1.1.3
      - exifread==3.0.0
      - fastjsonschema==2.18.0
      - flatbuffers==1.12
      - fqdn==1.5.1
      - gast==0.4.0
      - google-auth==2.22.0
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - grpcio==1.56.2
      - h5py==3.9.0
      - ipython-genutils==0.2.0
      - ipywidgets==8.1.0
      - isoduration==20.11.0
      - jinja2==3.1.2
      - joblib==1.3.2
      - json5==0.9.14
      - jsonpointer==2.4
      - jsonschema==4.19.0
      - jsonschema-specifications==2023.7.1
      - jupyter==1.0.0
      - jupyter-console==6.6.3
      - jupyter-events==0.7.0
      - jupyter-lsp==2.2.0
      - jupyter-server==2.7.3
      - jupyter-server-terminals==0.4.4
      - jupyterlab==4.0.5
      - jupyterlab-pygments==0.2.2
      - jupyterlab-server==2.24.0
      - jupyterlab-widgets==3.0.8
      - keras==2.9.0
      - keras-preprocessing==1.1.2
      - libclang==16.0.6
      - lxml==4.9.3
      - markdown==3.4.4
      - markupsafe==2.1.3
      - mistune==3.0.1
      - nbclient==0.8.0
      - nbconvert==7.8.0
      - nbformat==5.9.2
      - notebook==7.0.3
      - notebook-shim==0.2.3
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - overrides==7.4.0
      - pandocfilters==1.5.0
      - piexif==1.1.3
      - pkgutil-resolve-name==1.3.10
      - prometheus-client==0.17.1
      - protobuf==3.19.6
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pycparser==2.21
      - pydub==0.25.1
      - pyexiftool==0.5.5
      - pyfastcopy==1.0.3
      - pyqt5-sip==4.19.18
      - pyqtchart==5.12
      - pyqtwebengine==5.12.1
      - python-json-logger==2.0.7
      - pywinpty==2.0.11
      - qtconsole==5.4.4
      - qtpy==2.4.0
      - referencing==0.30.2
      - requests-oauthlib==1.3.1
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.10.0
      - rsa==4.9
      - scikit-learn==1.3.0
      - send2trash==1.8.2
      - sniffio==1.3.0
      - soupsieve==2.5
      - tensorboard==2.9.1
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.9.1
      - tensorflow-estimator==2.9.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==2.3.0
      - terminado==0.17.1
      - threadpoolctl==3.2.0
      - tinycss2==1.2.1
      - tomli==2.0.1
      - uri-template==1.3.0
      - urllib3==1.26.16
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.6.2
      - werkzeug==2.3.6
      - widgetsnbextension==4.0.8
      - wrapt==1.15.0
prefix: C:\Users\Hp\anaconda3\envs\cameratraps-env
